name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build ipyclipboard
        run: |
          python -m pip install build
          python -m build --wheel
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*

  build_lite:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./dist
      - name: Install the dependencies
        run: |
          python -m pip install jupyterlite-pyodide-kernel dist/*.whl
      - name: Build the JupyterLite site
        run: |
          mkdir content
          cp example.ipynb content
          jupyter lite build --contents content
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _output

  deploy_lite:
    needs: [build_lite]
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4